version: '3.8'

services:
  https:
    container_name: https
    image: steveltn/https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - rabbitmq
    restart: always
    volumes:
      - https:/var/lib/https-portal
      - https:/var/www/vhosts
    environment:
#      - STAGE=local
      - STAGE=production
      - DOMAINS=rabbitmq.${HOSTNAME:-localhost} -> http://rabbitmq:15672
    networks:
      - rabbitmq_net

  rabbitmq:
    container_name: rabbitmq
    image: marcelmaatkamp/rabbitmq-mqtt-ldap
    platform: linux/amd64
    restart: always
    hostname: rabbitmq
    command: bash -c "envsubst < /etc/rabbitmq/rabbitmq.config.envsubst > /etc/rabbitmq/rabbitmq.config && rabbitmq-server"
    ports:
      - 5671:5671
      - 8883:8883
    environment:
      - RABBITMQ_NODENAME=rabbitmq@rabbitmq
      - HOSTNAME=${HOSTNAME:-localhost}
    volumes:
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config.envsubst
      - rabbitmq:/var/lib/rabbitmq/mnesia
      - https:/var/lib/https
    networks:
      - rabbitmq_net


networks:
  rabbitmq_net:
    driver: bridge

volumes:
  https:
  rabbitmq:
